# 오류처리

### 오류처리

#### 1. 컴파일 오류 : 구문오류, API 사용 오류

#### 2. 실행 오류 : 에러, 예외

- **에러** - JVM 영역에서 발생하는 오류로서 치명적이어서

  ​		  JVM이 프로그램을 중단시키고 callstack 정보를 화면에 출력한다.

  ​		  미리 예측하고 대비하는 코드를 작성할 수 없다.

- **예외** - 자바 프로그램 영역에서 발생되는 실행 오류,

  ​		   다소 가벼운 잘못된 상황이 많다

  - 런타임 예외 : 발생원인이 프로그램 코드에 있는 것 - 버그
    - 예외처리 선택적
  - 일반 예외 : 발생 원인이 외부적인 요인이다
    - 예외처리 필수

- #### 예외 처리 방법

  1. 적극적인 예외 처리

     ```java
     try {
     	예외가 발생할 수도 있는 코드 입력
     }catch (처리해야하는 예외 클래스의 변수 선언){
     	처리 코드 입력
     }finally{
         예외 발생 여부와 관계 없이 마지막에 수행을 보장하는 코드
     }
     ```

  2. 소극적인 예외 처리

     메서드 헤더에 'throws 처리해야하는 예외 클래스' 절을 추가

     ```java
     package day11;
     
     public class ExceptionTest1 {
     
     	public static void main(String[] args) 
             throws InterruptedException {	//사용하여 오류 해결
     		System.out.println("수행시작");
     		Thread.sleep(3000);				//여기서 오류
     		System.out.println("수행종료");
     	}
     
     }
     ```

     

- #### 예외 발생

  - throw 발생시키고자 하는 예외 클래스의 객체

  - **throw new IOException(["예외메시지"])**
  - 예외를 발생시키는 코드를 가지고 있는 메서드는 헤더 **throws** 절을 사용해서 이 메서드는 호출시 예외가 발생할 수도 있다는 것을 알려야 한다.
  - throws 절은 예외를 발생시킬 때도 사용하고 처리할때도 사용



- #### 예외 발생 출력하는 구문

  (오류난 객체).getMessage    or    (오류난 객체).printStackTrace



---

###  예제

```java
package day11;

public class ExceptionTest1 {

	public static void main(String[] args) throws InterruptedException {
		System.out.println("수행시작");			//throws 를 줘서 오류날것 암시
		Thread.sleep(3000);
		System.out.println("수행종료");
	}

}
```

###### *메서드 헤더에 throw --Exception 을 줘서 오류날것을 암시해줘야 에러가 나지 않는다



```java
package day11;		
//에러들의 부모클래스는 Exception 이라는 클래스
public class ExceptionTest2 {

	public static void main(String[] args) {
		System.out.println("수행시작");
		try {	//예외가 발생할 수도 있는 코드, 꼭 예외 발생 코드만 있는건 아니다.
			int num1 = Integer.parseInt(args[0]);
			int num2 = Integer.parseInt(args[1]);
			int result = num1/num2;		//예외 발생하는 위치
			System.out.println("연산 결과 : "+result);
		}catch(ArrayIndexOutOfBoundsException e) {	
            			//만약 여기 캐치블럭에서 예외 처리하면 다시 올라감
			System.out.println("프로그램 아규먼트를 2개 전달하세요!!");
		}catch(ArithmeticException e) {	//0으로 나눌경우 발생
			e.printStackTrace(); //e 값을 사용하여 call stack 에러 정보 출력(비동기수행)
			System.out.println("두번쨰 프로그램 아규먼트는 0이 아닌 값을 전달하세요!!");
			return;
		}catch (Exception e) {	
            				//부모 클래스이기에 자손 클래스의 객체를 받을 수 있다.
									//부모 클래스일 수록 아래 위치시켜야 한다
									//위에 사용하면 모든 예외를 다 잡아내버린다
//		}catch (NumberFormatException e) {
			e.printStackTrace();
			System.out.println("프로그램 아규먼트로 숫자를 전달하세요!!");
		}finally {
			System.out.println("항상수행!!");	
		}
		System.out.println("수행종료!!");
	}

}
```

###### *이때 아규먼트 값을 Run configuration 에서 입력해주어야 테스트 할 수 있다.



```java
package day11;
import java.util.Random;
class TestException extends Exception {
	TestException(String message){
		super(message);		//에러메시지로 등록
	}
}
public class ExceptionTest3 {
	public static void main(String[] args)  {
		System.out.println("main()수행시작");
		a();
		System.out.println("main()수행종료");
	}
	static void a()  {	//try, catch로 할 경우는 throws 절 줄 필요없다.
		System.out.println("a()수행시작");
		try {
			b();
		} catch (TestException e){	
			System.out.println("오류 발생 : "+e.getMessage());
		}
		System.out.println("a()수행종료");
	}
	static void b() throws TestException {	//b가 호출한 c에 오류가 발생할 수 있지만 호출한 애한테 넘기겠다.
		System.out.println("b()수행시작");
		c();
		System.out.println("b()수행종료");
	}
	static void c() throws TestException { //throws TestException 을 안주면 오류 주고싶은 절에서 에러남
		System.out.println("c()수행시작");
		boolean flag = new Random().nextBoolean();	//변수에 안담고 바로 쓴 Random 구문,,한번만 사용 가능,,값은 true or false
		if(flag){
			throw new TestException("<<:::::테스트로 예외발생시킴:::::>>");
		}else {
			System.out.println("ㅋㅋㅋㅋ");
		}	
		System.out.println("c()수행종료");
	}	
}
```



##### 난수의 번호가 겹치지 않으면서 

##### 중복되는 경우 Exception 문구만 출력

##### 중복되지 않을 경우 로또 번호를 출력하는 실습

```java
package day11;

import java.util.Random;
//1. Exception 을 상속받는 오류 문구 내용 리턴하는 클래스 만들기
class DuplicateException extends Exception {
	DuplicateException() {
		super("중복된 로또 번호가 발생했습니다."); // string 형을 상속받으면 예외 메시지로 처리한다.
	}
}
//2. Exception 상속받으며 6개 숫자 받는 배열 만드는 생성자 갖는 클래스 생성
class LottoMachine extends Exception {
	private int nums[];

	LottoMachine() { // 6개의 int 형 원소 갖는 배열 생성
		this.nums = new int[6];
	}
//3. 배열에 원소 넣어주는 숫자 만들기 메서드 생성
	public void createLottoNums() { // 배열에 원소 넣기
		Random ran = new Random();
		for (int i = 0; i < 6; i++)
			nums[i] = ran.nextInt(20) + 1;
	}
//4. 중복 확인해주는 메서드 생성, throws 를 통해 예외 발생을 알려줘야함
	public void checkLottoNums() throws DuplicateException { // 메서드 헤더에 throws 를 보면 예외 클래스가 어떤건지 알 수있다
		for (int i = 0; i < 5; i++) { //
			for (int j = i + 1; j < 5; j++) {
				if (nums[i] == nums[j])
					throw new DuplicateException(); // 예외를 발생시키기위해 throw를 발생시킴..throw 뒤에는 꼭 예외객체가 있어야한다.
				// DuplicateException e = new DuplicateException();
				// throw e;
			}

		}
	}

	public int[] getNums() {
		return nums;
	}
}

public class LottoGame {

	public static void main(String[] args) {
		LottoMachine lotto = new LottoMachine(); // 배열생성
		lotto.createLottoNums(); // 난수 넣기

		try { // 예외 확인하는 try-catch 구문
			lotto.checkLottoNums(); // 예회 확인하는 checkLottoNums 메서드에서 오류발생하면 catch
		} catch (DuplicateException e) {
			System.out.println(e.getMessage()); // e.getMessage는 오류의 메시지
			return; // return 주는 이유는? 오류나면 여기서 실행 종료
		}
		int nums[] = lotto.getNums();
		for (int i = 0; i < nums.length; i++) {
			System.out.print(i == nums.length - 1 ? nums[i] : nums[i] + ",");

//		lotto.getNums();
//		for (int i = 0; i < lotto.getNums().length; i++) {
//			System.out.print(i == lotto.getNums().length - 1 ? lotto.getNums()[i] : lotto.getNums()[i] + ",");
		}
	}

}
```

